version: "3.8"
services:
  db:
    image: postgresql
    # volumes:
    #   - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=admin

    ports:
      - "5432:5432"
  api:
    build: ./backend/
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    image: api
    volumes:
      - ./backend:/backend
    user: "${UID_GID}"
    environment:
      RAILS_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - db