# dockerエンジンの対象バージョンに合わせる
version: '3.8'

services:
  db:
    image: postgres:15.3
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
      TZ: Asia/Tokyo
    ports:
      - '5432:5432'

  backend:
    build:
      context: ./api/
      dockerfile: Dockerfile
    container_name: rails-api
    ports:
      - '8080:8080'
    working_dir: /backend 
    stop_signal: SIGINT
    volumes:
      - ./backend:/backend
    stdin_open: true
    tty: true